### ISSUE TITLE
Make contributors aware of this fork

### ISSUE THREAD

**Issue by rugk** [rugk/threema-msgapi-sdk-php#2]
@medienverbinder
As Threema has decided to remove their SDKs from GitHub I know maintain a fork: https://github.com/rugk/threema-msgapi-sdk-php

I'd just wanted to let you know.

**Comment by medienverbinder** [comment]
Thanks for the information.

What is your plan ? A further development of Threema SDK, or just the official version of threema here on GitHub?

**Comment by rugk** [comment]
I've added some comments in the wiki: https://github.com/rugk/threema-msgapi-sdk-php/wiki/What-to-know-about-this-fork

So the current plan is: I will always host the official version at GitHub here in one branch and developing should be done in other branches.

**Comment by rugk** [comment]
As the purpose of this issue if this issue is fixed I'll close this.
