### ISSUE TITLE
Feature Level

### ISSUE THREAD

**Issue by lgrahl** [rugk/threema-msgapi-sdk-php#27]
We (Theema and I) have discussed using feature levels instead of having the same version numbers for different SDK languages. You can see the current definition below:

The feature level will be represented as a constant in the source code of the respective SDK. It should be printed, alongside the version number, when invoking the command line interface with the flag `-v` or `--version`. Alternatively, a command called `version` can be used instead of the flag.

| Level | Text | Capabilities | Image | File | Credits |
| --- | --- | --- | --- | --- | --- |
| 1 | X |  |  |  |  |
| 2 | X | X | X | X |  |
| 3 | X | X | X | X | X |

(The implementations for the official Java and PHP SDK are still missing, though.)

**Comment by rugk** [comment]
Okay, good idea. AFAIK the PHP SDK is at level 3.

**Comment by rugk** [comment]
@lgrahl Do you know when Threema wants to implement it in the PHP/Java SDK?

/cc @simmac

**Comment by lgrahl** [comment]
Nope. We may have to remind them. @threema-ch

**Comment by rugk** [comment]
I doubt they react to mentions on GitHub...

**Comment by simmac** [comment]
@lgrahl @rugk  I will do that as I have to contact Threema anyway regarding my fork of the java-sdk.

**Comment by rugk** [comment]
@simmac Thanks.

**Comment by simmac** [comment]
@rugk @lgrahl @threema-ch 
I just committed my own implementation of the version and feature level command in the Java-API: [7da9286](https://github.com/simmac/threema-msgapi-sdk-java/commit/7da92865bce58b7c374cc61325276e0e2fc38748).

**Comment by rugk** [comment]
Implemented:
![featurelevel](https://cloud.githubusercontent.com/assets/11966684/18619469/87926b1c-7dfd-11e6-9795-fd69cea90bd0.png)

But it only works with `-v` and no other switch.
