### ISSUE TITLE
Why has Threema discontinued the official repo?

### ISSUE THREAD

**Issue by rugk** [rugk/threema-msgapi-sdk-php#4]
I've already mailed them this question. I'll reply here if I know more.

CC: @threema

**Comment by medienverbinder** [comment]
I'd be highly interested as well... :-(

....Regards

**Comment by rugk** [comment]
I'm in contact with their support, but until now I did not got any explanation.
So if someone from @Threema wants to comment here it would also solve my support request. :smile:

**Comment by rugk** [comment]
I've received a reply (loosely translated):

> Because caring for multiple repositories is very time-consuming and the resources of Threema are limited, it was decided to withdraw from GitHub.

original German:

> Da das Pflegen mehrer Repositories einen grossen Zeitaufwand bedeutet und bei Threema die
> Resourcen jetzt schon sehr knapp sind, wurde ein Wegzug aus github beschlossen.

(Threema ticket number: `#722519`)

FYI Threema still accepts patches, so if you want I could submit them to them if they are added here.

**Comment by rugk** [comment]
Mentioned here: http://threema-forum.de/thread-1381.html
