### ISSUE TITLE
How to convert private key from text file into binary format?

### ISSUE THREAD

**Issue by MarcoDias7** [rugk/threema-msgapi-sdk-php#52]
I have this error when I try to implement the E2E in my PHP project. This is my method : 

```php
require_once APPPATH . "libraries/Threema/vendor/autoload.php";

		//define your connection settings
		$settings = new Threema\MsgApi\ConnectionSettings(
		'*ThreemaID',
		'secretkey'
		);

		$publicKeyStore = new Threema\MsgApi\PublicKeyStores\File(FCPATH . "data/threema_public_key.txt");
		$connector = new Threema\MsgApi\Connection($settings, $publicKeyStore);

		$threemaId = '*ThreemaID';
		$msg = "This is an end-to-end encrypted message";
		$senderPrivateKey = FCPATH . "data/threema_private_key.txt";

		$e2eHelper = new Threema\MsgApi\Helpers\E2EHelper($senderPrivateKey,$connector);
		$result = $e2eHelper->sendTextMessage($threemaId, $msg);

		if(true === $result->isSuccess()) {
			echo 'Message ID: '.$result->getMessageId() . "\n";
		}
		else {
			echo 'Error: '.$result->getErrorMessage() . "\n";
		}
```

The connection is working I think the problem is with the $sendPrivateKey. In the documentation, it is written that we shoud put the privatekey like this $senderPrivateKey = "MY_PRIVATE_KEY_IN_BIN";

What does that mean ? I have my private key generated in a .txt file in the format : 
private:xxxxx (64 characters)

How should I convert my file, or how should he look like ?

**Comment by rugk** [comment]
Basically you need to read the key, strip the suffix and convert it from hex into binary.
Reading and stripping the suffix should not be a big deal, but for converting the key please use [the hex2bin implementation](https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptTool.php#L477-L496) of the CryptTool as it is constant-time (to be resistant against timing attacks) when Libsodium is used.
You can find a example implementation of this in [this project of me](https://github.com/rugk/xenforo-threema-gateway/blob/master/src/library/ThreemaGateway/Handler/PhpSdk.php#L254).

---

BTW I've added syntax highlighting to your code example. You can easily do that by putting the language name you use after the beginning  \`\`\`.

**Comment by MarcoDias7** [comment]
Thanks a lot, I made it work!

My CryptTool.php doesn't have the hex2bin function you're saying, is this a new version of the file ?

**Comment by rugk** [comment]
Yes the GitHub version I use here is a newer one, where I've patched and improved some things. Unfortunately Threema could not release it yet, but they are aware of these changes.

As an alternative for now you could of course use [Libsodium directly](https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptToolSodium.php#L139) or - if you really cannot do it in another way - PHPs native hex2bin().

**Comment by MarcoDias7** [comment]
Ok thanks a lot !
