### ISSUE TITLE
PHP7.2 libsodium support

### ISSUE THREAD

**Issue by pavarnos** [rugk/threema-msgapi-sdk-php#56]
Hi. I managed to get this working on PHP7 by modifying the CryptToolSodium.php. Is this repo still maintained? Are you accepting pull requests? How do you sync with the official (.zip download) version from Threema? Whats the best way to add a PHP7 CryptTool*.php driver?

**Comment by rugk** [comment]
> How do you sync with the official (.zip download) version from Threema?

Usually just send them the PRs manually and download ZIPs and integrate them if they are needed there. See https://github.com/rugk/threema-msgapi-sdk-php/wiki/Contributing#where-to-contribute where this is described a bit.

As for PHP7: AFAIK it should work, but maybe a newer PHP version prevented it.

**Comment by pavarnos** [comment]
OK. I emailed them an updated CryptToolSodium.php so will see what happens before making a pull request here. With sodium built in, a PHP7 only version of the PHP api can delete a lot of cruft eg the Salt submodule, the obsolete CryptTool drivers, the way the drivers are tested before selection, the extra autoloaders etc.
Thanks for the quick reply. And thanks also for the obvious effort you have put in to make a high quality package here.

**Comment by rugk** [comment]
Anyway, I'd say make the PR here. This is inofficial anyway.
But if your PR only consists of removing code, I doubt they'll accept it. Making it incompatible with older PHP versions is likely not the thing one wants.

**Comment by pavarnos** [comment]
Fair comment. Integrated libsodium is a php7.2 thing https://paragonie.com/book/pecl-libsodium/read/00-intro.md. I'm still waiting to hear back from them. Apparently "the person who looks after the php api" is on holiday at the moment...

**Comment by pavarnos** [comment]
Thanks for all your advice. After much thought, I decided a fork was easier https://github.com/pavarnos/threema-msgapi-sdk-php. I wanted to make some fairly big changes that I was unsure would be accepted. I also need this quickly: got a deadline to meet.

**Comment by rugk** [comment]
Okay, let me know if they accept (a part of) that.

**Comment by pavarnos** [comment]
Will do. Added the bulk lookup in a single commit so you can easily backport it if you want https://github.com/pavarnos/threema-msgapi-sdk-php/commit/feef7b55157ca2e705b63da67be4bdc2498a9fc3
