### ISSUE TITLE
bulk lookup not implemented

### ISSUE THREAD

**Issue by pavarnos** [rugk/threema-msgapi-sdk-php#57]
Is there any reason bulk lookup is not implemented? `https://msgapi.threema.ch/lookup/bulk`
Should be easy enough to do?

**Comment by rugk** [comment]
The bulk lookup API was introduced after the last update of this library, i.e. that feature is "too new". 😄

**Comment by pavarnos** [comment]
lol. see #56. Thanks for your advice btw.
