### ISSUE TITLE
composer require => PHP Fatal error:  require_once(): Failed opening required 'Salt/autoload.php'

### ISSUE THREAD

**Issue by medienverbinder** [rugk/threema-msgapi-sdk-php#58]
When I try to install the SDK via Composer, the directory "Salt" is empty and I get an error message within my project:

PHP Warning:  require_once(Salt/autoload.php): failed to open stream: No such file or directory in /var/www/htdocs/project/vendor/rugk/threema-msgapi-sdk-php/source/bootstrap.php on line 2

PHP Fatal error:  require_once(): Failed opening required 'Salt/autoload.php' (include_path='.:/usr/share/php') in /var/www/htdocs/project/vendor/rugk/threema-msgapi-sdk-php/source/bootstrap.php on line 2

Tested with Debian and OSX via "**composer require rugk/threema-msgapi-sdk-php**"

Does anyone have any idea how it happens that the "Salt" directory is empty?
(by the way: when I add the missing files [manually](https://github.com/rugk/Salt/archive/85a379a750ff9b513f92ee104dab68b00418aaa8.zip), everything works )

**Comment by rugk** [comment]
Yes, this is an expected error. Salt is only the pure-PHP fallback implementation of Libsodium. See https://github.com/rugk/Salt.
It seems composer does not include git submodules when generating the published release. (You can [see it here](https://github.com/rugk/threema-msgapi-sdk-php/tree/master/source)).

Note that, if you do not use the fallback, you can easily fake the whole dir by adding empty files or so.

https://github.com/rugk/threema-msgapi-sdk-php/issues/51 could maybe solve this issue as that module is also available on composer.
